Feature/exposing gesture events
WhereIsMyTransport/flutter-mapbox-gl pull request #7
Opened 2022-01-20 08:45 UTC by TinasheKeith

Exposed mapbox gesture to flutter-mapbox-gl:
- onRotateBegin
- onRotate
- onRotateEnd
- onScaleBegin
- onScale
- onScaleEnd
- onMapMoveBegin
- onMapMove
- onMapEnd
- onShoveBegin
- onShove
- onShoveEnd

2022-01-21 06:48 UTC, arnewimt commented on android/src/main/java/com/mapbox/mapboxgl/MapboxMapBuilder.java
> +  public void onScale() {
@TinasheKeith is this empty block intentional?

2022-01-21 07:05 UTC, arnewimt approved these changes
@TinasheKeith nice work! I've left a few comments that may need to be addressed, but I'm improving in the meantime as I trust you'll handle it.

2022-01-21 07:05 UTC, arnewimt commented on mapbox_gl_platform_interface/lib/src/method_channel_mapbox_gl.dart
> +      case 'map#onRotateBegin':
You Already have 'map#onRotateBegin' a bit higher up. I think you may have intended for this to be  'map#onScaleEnd'.

```
      case 'map#onScaleEnd':
        final CameraPosition cameraPosition =
            CameraPosition.fromMap(call.arguments['position']);
        onScaleEndPlatform(cameraPosition);
        break;
```

2022-01-21 07:57 UTC, irjayjay requested changes
Main issue is the incorrectly mapped methods in the mapbox_map_controller.dart
The others are just nice-to-haves.
Arne also mentioned that you mapped the same method twice somewhere.

2022-01-21 07:57 UTC, irjayjay commented on lib/src/controller.dart
> +        onRotate();
Do we not want to pass arguments to the lambda methods? How will we know how far we rotated, etc?
Or are we only doing what's necessary to get current features working and we'll upgrade these later?

2022-01-21 07:57 UTC, irjayjay commented on mapbox_gl_web/lib/src/mapbox_map_controller.dart
> +    var camera = CameraPosition(
What if getting camera position from the _map object was a method that you could just call instead of duplicating the same 6 lines of code each time?

2022-01-21 07:57 UTC, irjayjay commented on lib/src/controller.dart
> +typedef void OnRotateBeginCallback();
See here I think(maybe not now, maybe in future) we could include parameters for at least previousCameraPosition and newCameraPosition, or something along those lines, so that we can use it in future when we need to calculate distance travelled, amount of rotation, etc.

2022-01-21 07:57 UTC, irjayjay commented on lib/src/controller.dart
> +typedef void OnScaleCallback();
Could we put this OnScaleCallback together with the other OnScaleBeginCallback and OnScaleEndCallback?

2022-01-21 07:57 UTC, irjayjay commented on lib/src/controller.dart
> +    this.onScale,
Here too, put onScale with its family. Not a biggie, but nice to have things in order.

2022-01-21 07:57 UTC, irjayjay commented on lib/src/controller.dart
> +    this.onRotate,
onRotate can be with its family

2022-01-21 07:57 UTC, irjayjay commented on mapbox_gl_platform_interface/lib/src/method_channel_mapbox_gl.dart
> +      case 'map#onRotateBegin':
If you keep everything in the same order, it would be harder to make mistakes. Whenever dealing with lists, I try to keep the list in a certain order, so that if I miss something, I'll notice.

2022-01-21 07:57 UTC, irjayjay commented on mapbox_gl_web/lib/src/mapbox_map_controller.dart
> +    _map.on('mapmovebegin', _onMapMove);
'mapmovebegin' maps to onMapMove here, please fix.

2022-01-21 07:57 UTC, irjayjay commented on mapbox_gl_web/lib/src/mapbox_map_controller.dart
> +    _map.on('mapmoveend', _onMapMove);
'mapmoveend' maps to onMapMove here, please fix.

2022-01-21 08:08 UTC, irjayjay requested changes
Sorry, second review, found another mismatch.

2022-01-21 08:08 UTC, irjayjay commented on lib/src/controller.dart
> +        onRotate();
Shouldn't this be onRotateBegin()?

2022-01-21 08:49 UTC, lorenzorheinicke commented on lib/src/controller.dart
> +typedef void OnRotateBeginCallback();
Can we add a TODO here so that we don't forget to do that at some point

2022-01-23 18:40 UTC, TinasheKeith commented on lib/src/controller.dart
> +typedef void OnRotateBeginCallback();
@irjayjay Definitely noted, just a bit constrained for time but I've added it as an [OPEX item](https://dev.azure.com/whereismytransport/Arrakis/_boards/board/t/Arrakis%20Team/Stories/?workitem=30775) on our Azure boards but also wondering if it should maybe be a MaHS item to be done after our current release

2022-01-23 19:17 UTC, TinasheKeith commented on android/src/main/java/com/mapbox/mapboxgl/MapboxMapController.java
> +    methodChannel.invokeMethod("map#onMoveEnd", arguments);
Thanks for catching that! Updated

2022-01-23 19:19 UTC, TinasheKeith commented on mapbox_gl_platform_interface/lib/src/method_channel_mapbox_gl.dart
> +      case 'map#onRotateBegin':
I should have done that, I think the way I went about this was a bit all over the place as I was trying to figure a lot of this out at the same time, but could have cleaned up a lot better. I went back and sorted these

2022-01-23 19:21 UTC, TinasheKeith commented on mapbox_gl_web/lib/src/mapbox_map_controller.dart
> +    var camera = CameraPosition(
Cleaned this up too 😅

2022-01-24 07:33 UTC, jjwimt approved these changes
Only had one suggestion, to get rid of repetitive code. This is not a necessity though, so this PR is approved by me.

2022-01-24 07:33 UTC, jjwimt commented on android/src/main/java/com/mapbox/mapboxgl/MapboxMapController.java
> +    final Map<String, Object> arguments = new HashMap<>(2);
Each of these methods are doing the exact same logic except for the method name string.
Could this logic be added to a method that accepts the arguments and method string, then just run that method in a single line each instance?

2022-01-24 07:57 UTC, TinasheKeith commented on android/src/main/java/com/mapbox/mapboxgl/MapboxMapController.java
> +    final Map<String, Object> arguments = new HashMap<>(2);
Updated and tested, thanks!

2022-01-24 08:15 UTC, merged